### ISSUE TITLE
docklet_shinyapp()

### ISSUE THREAD

**Issue by flaviobarros** [sckott/analogsea#100]
Recently i wrote a post about dockerizing a shiny app (http://www.flaviobarros.net/2015/04/30/dockerizing-a-shiny-app/). I saw that there is already a function to deploy a RStudio Server: docklet_restudio()

Is there some plan for a dockelet_shinyserver()? 

Wouldn't be difficult to create something like docklet_shinyapp(). I'm thinking about a way to create a shiny app, and with an command create an image on digital ocean with the app. We will just need an shiny image exposing PORT 80 and copy all app files (server.R and ui.R) to the right folder, and done.

**Comment by sckott** [comment]
hi @flaviobarros - doing a `dockelet_shinyserver()` should be easy - can start working on that soon.
