### ISSUE TITLE
Cannot create rstudio docklet on windows

### ISSUE THREAD

**Issue by studerus** [sckott/analogsea#114]
I'm working on windows 10 with the latest version of R and analogsea from github. Creating and manipulating droplets works fine, but I cannot create an RStudio or shiny server. Running the following command:

``` r
droplets()[[1]] %>%
 docklet_rstudio()
```

results in the following error message:

``` r
Error: ssh failed
ssh -o BatchMode=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=C:\Users\[...]\AppData\Local\Temp\RtmpgVJp1H/hosts root@46.101.209.177 "docker pull rocker/rstudio"
In addition: Warning message:
running command 'ssh -o BatchMode=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=C:\Users\[...][\AppData\Local\Temp\RtmpgVJp1H/hosts root@46.101.209.177 "docker pull rocker/rstudio"' had status 255 
```

Is this a bug or am I doing something wrong?

**Comment by sckott** [comment]
Do you have SSH keys set up already on your machine?  And you can ssh into a DO box?

**Comment by studerus** [comment]
How can I check whether I have SSH keys correctly set up? It appears that I have SSH keys because typing `keys()` shows two different keys.

It would be very helpful if either the vignette or the help file  `docklet_rstudio()` would explain how to use SSH keys for creating an RStudio server.

**Comment by sckott** [comment]
> How can I check whether I have SSH keys correctly set up?

if you can ssh into your DigitalOcean machine from the command line outside of R, then I think everything should work fine in `analogsea` in R - can you do that?

> It would be very helpful if either the vignette or the help file `docklet_rstudio()` would explain how to use SSH keys for creating an RStudio server.

Will definitely add more to the docs on using ssh keys

**Comment by sckott** [comment]
Note there's a slight problem too when creating docklet's where they aren't actually all the way up even when we think they are https://github.com/sckott/analogsea/issues/113 - working on fixing that - solution being just creating the droplet with `docklet_create()` - then check again with `droplets()` until is says status active, then you can go ahead and do things with it

to be sure, you did create a docker droplet via `docklet_create()`

**Comment by studerus** [comment]
Sorry, I'm not familiar with using ssh on the command line. Do you have an example command that I could adapt for my needs?

**Comment by sckott** [comment]
> Do you have an example command that I could adapt for my needs?

e.g., `ssh -i .ssh/id_rsa2 root@<IP Address>` 

* IP address: e.g., `46.101.209.177` the one you had above in your error message
* `root` is the user name - so if you chose a different user name, use that, but most likely it is `root`
* the `-i` is a flag to pass in your ssh key and the `.ssh/id_rsa2` is the path to my ssh key

**Comment by sckott** [comment]
Note: I don't know much about where windows ssh keys are stored

**Comment by studerus** [comment]
Using ssh on the command line seems to have worked, because it says "Welcome to Ubuntu 14.04 ..." at the end. However, it also said before "Could not create directory './home/erich/.ssh'". The authenticity of host ... could not be established. It also said "Failed to add the host to the list of known hosts (...)"

**Comment by studerus** [comment]
I created the ssh key pair with RStudio under Global Options - Git/SVN. It's stored in C:/Users/erich/.ssh/id_rsa by default

**Comment by studerus** [comment]
>Note there's a slight problem too when creating docklet's where they aren't actually all the way up even when we think they are #113 - working on fixing that - solution being just creating the droplet with docklet_create() - then check again with droplets() until is says status active, then you can go ahead and do things with it to be sure, you did create a docker droplet via docklet_create()

I tried that. Unfortunately, I did not help.

**Comment by sckott** [comment]
Thanks for the info. Do you have your ssh keys stored in options?  what does `getOption("do_ssh_keys", NULL) ` give you?

**Comment by studerus** [comment]
No, I didn't have stored it in options, but I tried it out now. Unfortunately, it still didn't work.

**Comment by sckott** [comment]
Okay, i'll have to test on a windows VM, and get back to you ... :clock1030:

**Comment by trestletech** [comment]
Pro-top for others who might have Googled their way here: remember that if you're using RStudio Server, you are technically trying to SSH from your server, not from your desktop. So make sure your SSH keys are setup to work when using the remote server, not your desktop.

Wasted a few more minutes on that than I'd like to confess.

**Comment by sckott** [comment]
Thanks, but isn't the problem here that ssh keys on desktop and server are not configured correctly (which I think doesn't have anything to do with rstudio server)?

**Comment by trestletech** [comment]
Sorry, my point was that I had the keys working swimmingly on my desktop and usually use RStudio Desktop. So I was puzzled when I could SSH in from the command line but analogsea could never SSH in to the droplet. 

Of course, once I get the SSH keys setup on the server and confirmed that I could SSH into the droplet from the server, then the analogsea commands running in RStudio Server started working.
