### ISSUE TITLE
Functions involving key printing/handling (including droplet_create) broken with openssl >= 0.9.5

### ISSUE THREAD

**Issue by trestletech** [sckott/analogsea#126]
analogsea imports httr which imports openssl. 

It seems that something about the handling of SSH keys changed in the openssl package, though I don't see an obvious relationship. It's entirely possible that there's just a collision of class names here. But when I go to `droplet_create()` against the latest openssl on CRAN, I get an error.

```
> analogsea::droplet_create()
Error in derive_pubkey(key) : 
  RAW() can only be applied to a 'raw', not a 'list'
> traceback()
10: .Call(R_derive_pubkey, key)
9: derive_pubkey(key)
8: as.list.key(x)
7: as.list(x)
6: `[[.key`(X[[i]], ...)
5: FUN(X[[i]], ...)
4: vapply(x, "[[", name, FUN.VALUE = type)
3: pluck(ssh_keys, "name", character(1))
2: standardise_keys(ssh_keys)
1: analogsea::droplet_create()
```

I can reproduce this error on versions 0.9.5 and 0.9.6 of openssl. The workaround is to install version 0.9.4 of openssl:

```
> devtools::install_github("jeroen/openssl", ref="v0.9.4")
...
> # RESTART R SESSION
> analogsea::droplet_create()
> # Works -- aside from issue #125
```

openssl is currently on version 0.9.6 on CRAN, and 0.9.5 was released around 2016-10-28.

**Comment by sckott** [comment]
thanks @trestletech 

I can't replicate the error above, with `openssl` `v0.9.6` or other `openssl` versions

any thoughts?

**Comment by trestletech** [comment]
Hm... I'm on a clean session in R 3.3.2 on OSX. This is just after installing analogsea and openssl from CRAN.

```
> library(openssl)
> library(analogsea)

Attaching package: ‘analogsea’

The following object is masked from ‘package:graphics’:

    image

> drop <- droplets()[[1]]
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
> droplet_ssh(drop, "ls")
Warning: Permanently added '45.55.16.127' (ECDSA) to the list of known hosts.
alexa
plumber
> droplet_create()
Error in derive_pubkey(key) : 
  RAW() can only be applied to a 'raw', not a 'list'
> devtools::session_info()
Session info ---------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.2 (2016-10-31)
 system   x86_64, darwin13.4.0        
 ui       RStudio (1.0.136)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/Chicago             
 date     2017-04-26                  

Packages -------------------------------------------------------------------------------------
 package   * version date       source        
 analogsea * 0.5.0   2016-11-11 CRAN (R 3.3.2)
 curl        2.3     2016-11-24 CRAN (R 3.3.2)
 devtools    1.12.0  2016-06-24 CRAN (R 3.3.0)
 digest      0.6.11  2017-01-03 CRAN (R 3.3.2)
 httpuv      1.3.3   2015-08-04 cran (@1.3.3) 
 httr        1.2.1   2016-07-03 CRAN (R 3.3.0)
 jsonlite    1.4     2017-04-08 cran (@1.4)   
 magrittr    1.5     2014-11-22 CRAN (R 3.3.0)
 memoise     1.0.0   2016-01-29 CRAN (R 3.3.0)
 openssl   * 0.9.6   2016-12-31 CRAN (R 3.3.2)
 R6          2.2.0   2016-10-05 CRAN (R 3.3.0)
 Rcpp        0.12.9  2017-01-14 cran (@0.12.9)
 withr       1.0.2   2016-06-20 CRAN (R 3.3.0)
 yaml        2.1.14  2016-11-12 CRAN (R 3.3.2)
```

**Comment by sckott** [comment]
@trestletech okay, can replicate on vanilla session

Does appear to be a collision of s3 `key` methods

**Comment by sckott** [comment]
@trestletech made some changes on branch `keys` https://github.com/sckott/analogsea/tree/keys 

changed all `as.key` methods to `as.sshkey` and `print.key` to `print.sshkey` - didn't change all methods with key in name to keep fxn name changes to a minimum. 

this does seem to fix it for me at least. 

does this solution sound good to you?  suggestion for a different way to solve it?

there's no cran rev deps of this pkg, so as far as I know, you're the only one affected by breaking the public API

**Comment by trestletech** [comment]
Installed your branch and things seem to be working well so far! The solution seems sensical as best I can tell, though I'm no s3 dispatch expert.

No worries about the API compatibility of this class on my end, so I'm :+1:
