### ISSUE TITLE
debian_add_swap not persisted across reboots

### ISSUE THREAD

**Issue by trestletech** [sckott/analogsea#127]
It looks like `debian_add_swap()` doesn't do this so it works on the initial boot but is gone after reboot.

Running `swapon /swapfile` fixes things, but only until the machine shuts down again.

I believe that the swap entry needs to be added to `/etc/fstab` in order to survive a reboot.

**Comment by sckott** [comment]
thanks @trestletech 

Is `/etc/fstab` a dir or file? So just create the swapfile, then add to a `/etc/fstab`?

**Comment by trestletech** [comment]
Yeah, it's a file. Looks like it's just a one line append to `/etc/fstab`. See "Make the Swap File Permanent" here: https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04

**Comment by sckott** [comment]
Ah, cool, thanks very much

**Comment by sckott** [comment]
@trestletech okay, fixed, let me know if that doesn't work
