### ISSUE TITLE
Change default image for droplet create to `ubuntu-16-04-x64`

### ISSUE THREAD

**Issue by sckott** [sckott/analogsea#151]
for `droplet_create`/`droplets_create`/`docklet_create`/`docklets_create`, any others?

right now we have `ubuntu-14-04-x64`

**Comment by sckott** [comment]
thoughts anyone? @amoeba @thercast @trestletech

**Comment by amoeba** [comment]
I'd say 👍 . DigitalOcean offers great tutorial pages and I expect, now that 16.04.3 is their default image, their help pages will be focused around that version of Ubuntu (if they aren't already).

**Comment by thercast** [comment]
I agree.  Now my ubuntu servers are on 16.04 so it makes sense to keep in line with the latest LTS release.

**Comment by sckott** [comment]
okay, will update to that image
