### ISSUE TITLE
Change default size to `1gb` ?

### ISSUE THREAD

**Issue by sckott** [sckott/analogsea#152]
right now we have `512mb`

thoughts anyone? @amoeba @thercast @trestletech

**Comment by amoeba** [comment]
Good catch. It doesn't even look like they offer a 512MB option now that the doubled their Droplet sizes last month. I see the 1GB as their smallest now. I think the average `analogsea` user probably doesn't need more than the 1GB to start.

**Comment by sckott** [comment]
Right, i thkn it makes sense to give them the smallest size possible by deafult in those cases where they are surprised that it costs money 🙈 

you can see that they still have 512 mb if you run `analogsea::sizes()` but they don't show it in the web UI

**Comment by amoeba** [comment]
Oh, tricky. I wonder if that would be confusing to a user f they couldn't find the Droplet size they see in R on the web. The Python, Ruby, and Go DigitalOcean packages all still use 512 so maybe just follow the crowd? Obviously, they could just be about to make the jump to 1GB. 

I think the any pros of moving to 1GB as the default could be outweighed by the increased cost. Plus: DigitalOcean provides easy Droplet resizing.

**Comment by sckott** [comment]
> I wonder if that would be confusing to a user f they couldn't find the Droplet size they see in R on the web

could try to ameliorate by documenting well :)

**Comment by thercast** [comment]
Chiming in late but my vote is to keep the default at 512 mb for the reasons mentioned ☝️ .  It's easy enough to resize up for users if needed.

**Comment by trestletech** [comment]
Assuming that the unlisted 512MB instance is actually cheaper, I'd vote for the cheapest/smallest option until if/when you're spending lots of times dealing with bugs about people running out of memory. 

But if the price is a wash or if you're spending lots of time helping people deal with OOM errors, I don't feel strongly.

**Comment by sckott** [comment]
thanks @thercast and @trestletech 

Seems like there is one option with `1gb` that is the same price, and two other options where its 2x and 3x the price

```r
head(sizes())
#>          slug memory vcpus disk transfer price_monthly price_hourly available
#> 1       512mb    512     1   20        1             5      0.00744      TRUE
#> 2 s-1vcpu-1gb   1024     1   25        1             5      0.00744      TRUE
#> 3         1gb   1024     1   30        2            10      0.01488      TRUE
#> 4 s-3vcpu-1gb   1024     3   60        3            15      0.02232      TRUE
```

**Comment by trestletech** [comment]
Well then I vote 1GB!

**Comment by sckott** [comment]
okay, i'll test and make sure that price is the right price, it's not clear what exactly `s-1vcpu-1gb` means
