### ISSUE TITLE
Sanity Check: Simplest way to spin up a `future` cluster

### ISSUE THREAD

**Issue by CerebralMastication** [sckott/analogsea#167]
This is less an 'issue' and more a 'code review' sort of discussion. I'm working with O'Reilly & Paul Teeter to update the R Cookbook for a 2nd edition. One recipe I'd really like to have is "execute code in parallel in the cloud".  It seems to me that `future` with `furrr` is a really good fit as it makes the `purrr` approach parallel. 

Towards that end I'm trying to figure out the most drop dead simple recipe for spinning up a cluster for use with `future`. Thanks to some [good ideas from Andrew Heiss](https://www.andrewheiss.com/blog/2018/07/30/disposable-supercomputer-future/) I have cooked up the following:

```r
library(analogsea)
library(tidyverse)
library(furrr)

cluster_tag <- 'r_cluster' 
cluster_prefix <- 'node-'
number_of_nodes <- 4

my_droplets <- docklets_create(names = paste0(cluster_prefix, as.character(1:number_of_nodes)),
                               region = "sfo2",
                               size = "1gb",
                               tags = cluster_tag)

# pull the ip addresses for the droplets
ips <- droplets(tag=cluster_tag) %>%
  map(function(x) x$networks$v4[[1]]$ip_address) %>%
  unlist

# Path to private SSH key that matches key uploaded to DigitalOcean
# it looks like ~ does not work here... not sure why
ssh_private_key_file <- "/Users/jal/.ssh/id_rsa"

# Connect and create a cluster
cl <- makeClusterPSOCK(
  # vector of IPs in our cluster
  workers = ips,

  # DigitalOcean droplets use root for user
  user = "root",

  # use the key connected to Digital Ocean
  rshopts = c(
    "-o", "StrictHostKeyChecking=no",
    "-o", "IdentitiesOnly=yes",
    "-i", ssh_private_key_file
  ),

  # run Rscript in the tidyverse docker
  rscript = c("sudo","docker","run","--net=host","rocker/tidyverse","Rscript"),
  
    rscript_args = c(
    # Install furrr (future too) 
    "-e", shQuote("install.packages('furrr')")
  ),
  homogeneous=FALSE, 
  verbose=TRUE
)

```
My question for you all is simply: Can I make this more simple? This work. It makes a parallel backend. I can explain each step. But can it be even more simple? 

Thanks!

**Comment by sckott** [comment]
@CerebralMastication  crap, so this must be the longest i've gone w/o replying to an issue. many apologies. 

I can't think of anything to make simpler. 

Is this still the up to date version of your thinking on this?

**Comment by CerebralMastication** [comment]
I think so...

**Comment by sckott** [comment]
cool, anything else to discuss on this ?

**Comment by p-schaefer** [comment]
I am trying to follow this example, but am running into an error. I feel like its something very simple that I am missing. I'm trying to create a new droplet from within an existing droplet to perform remote calculations on. When I run the 
`makeClusterPSOCK()` part, I get the folloring:

`[local output] Workers: [n = 1] ‘167.99.176.218’
[local output] Base port: 11963
[local output] Creating node 1 of 1 ...
[local output] - setting up node
[local output] - attempt #1 of 3
[local output] Will search for all 'rshcmd' available

[local output] Found the following available 'rshcmd':
[local output]  1. ‘/usr/bin/ssh’ [type=‘ssh’, version=‘OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017’]
[local output] Using 'rshcmd': ‘/usr/bin/ssh’ [type=‘ssh’, version=‘OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017’]
[local output] Starting worker #1 on ‘167.99.176.218’: '/usr/bin/ssh' -R 11963:localhost:11963 -l root -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -i /home/pschaefer/.ssh/id_rsa 167.99.176.218 "'sudo' 'docker' 'run' '--net=host' 'rocker/tidyverse' 'Rscript' --default-packages=datasets,utils,grDevices,graphics,stats,methods -e \"install.packages('furrr')\" -e 'workRSOCK <- tryCatch(parallel:::.slaveRSOCK, error=function(e) parallel:::.workRSOCK); workRSOCK()' MASTER=localhost PORT=11963 OUT=/dev/null TIMEOUT=2592000 XDR=TRUE"
[local output] - Exit code of system() call: 0
[local output] Waiting for worker #1 on ‘167.99.176.218’ to connect back
Warning: Permanently added '167.99.176.218' (ECDSA) to the list of known hosts.
/home/pschaefer/.ssh/id_rsa: 1: /home/pschaefer/.ssh/id_rsa: -----BEGIN: not found
/home/pschaefer/.ssh/id_rsa: 2: /home/pschaefer/.ssh/id_rsa: Proc-Type:: not found
/home/pschaefer/.ssh/id_rsa: 3: /home/pschaefer/.ssh/id_rsa: DEK-Info:: not found
/home/pschaefer/.ssh/id_rsa: 5: /home/pschaefer/.ssh/id_rsa: Vf8lCI6uuIXv/TgVkC5EzH7Bm8rr0PcXg4gFJtA7eP31ADyAzUdz548qaNhWiv27: not found
/home/pschaefer/.ssh/id_rsa: 6: /home/pschaefer/.ssh/id_rsa: 1N1cQsAD5c8OsCy1+x6lXg7zBX605Mk/A80Y0Db3sLkJXdxOWHZJH++X0787H+rM: not found
/home/pschaefer/.ssh/id_rsa: 7: /home/pschaefer/.ssh/id_rsa: dOb+g9X6vud26pACuA5NY7YTYac5YA/H0GNq12LhXHlOTjtSGLTIkkbBdDL+dqSJ: not found
/home/pschaefer/.ssh/id_rsa: 8: /home/pschaefer/.ssh/id_rsa: OCWytzLCX5sjxlqGqd0NcJkSODAqe2g8cG4k8rnT4llomwKFr+7iXrWXg265VxcL: not found
/home/pschaefer/.ssh/id_rsa: 9: /home/pschaefer/.ssh/id_rsa: W9rr8MA72Vv4t0CpN4ztEb1geBIZk8B1q/QTqLvSFEoBzocITrYCbJUnreW2DI9d: not found
/home/pschaefer/.ssh/id_rsa: 10: /home/pschaefer/.ssh/id_rsa: xo7Jqng+EvBrsYTWHPnQ1axdnmu/5Agf36AyvyZxYHTOWy42LTJKscFnsFxfb50F: not found
/home/pschaefer/.ssh/id_rsa: 11: /home/pschaefer/.ssh/id_rsa: dsSfxIe4eBinZaUzNm3n/s1xgu6d0U7rCSW/CJfSM6fd8vk8mDJS2hj8Xk3NS4lt: not found
/home/pschaefer/.ssh/id_rsa: 12: /home/pschaefer/.ssh/id_rsa: Tc01TayzO9IIEiIyxYFORDNVjtPrP/Auk5FZZtBG4o/6we0zPiwiQ6TSnWtuBZ5X: not found
/home/pschaefer/.ssh/id_rsa: 13: /home/pschaefer/.ssh/id_rsa: rPGj7VsRMPmz6uhJ7L7q03wIPEUxv9ah4pcuMtJb4TBOCbV6YweXJJ0wKPVXklzI: not found
/home/pschaefer/.ssh/id_rsa: 14: /home/pschaefer/.ssh/id_rsa: m6n4YrdTn1v+VOVg2qoa3eMaJcKMYmGPChCjGSuPgqJVdZy3wLU9rCQfRqyfRiSj: not found
/home/pschaefer/.ssh/id_rsa: 15: /home/pschaefer/.ssh/id_rsa: SMbhVoNZzjPjPbkMmwvRFZdpmtgU8ER/xltyLvUeWcqgc5tqgIDqh6NiU60CBj65: not found
/home/pschaefer/.ssh/id_rsa: 16: /home/pschaefer/.ssh/id_rsa: USrMw1nPnk5kaYWw+9apF9kIoMtCY9gHZf7/IczmAZBhgyBusljbJmfTiJDfOdHe: not found
/home/pschaefer/.ssh/id_rsa: 17: /home/pschaefer/.ssh/id_rsa: uCebkAbLmDh8c+frWxEkjB3WZRA8a0QbqHuPtSIbf0vENkJSXVCqpthWtQuU4gCf: not found
/home/pschaefer/.ssh/id_rsa: 18: /home/pschaefer/.ssh/id_rsa: DiNGjHadyBmhLUlEefoh1OlvfANibUqQgPI7OrKDQ3CsvKWS/BmaIbu0aZMRew4K: not found
/home/pschaefer/.ssh/id_rsa: 19: /home/pschaefer/.ssh/id_rsa: gMQkX68jdTYyt14NBW0CM9oxIVrUnSnrPsdLhbqgD0dff/K4lFTQeWWt9mPcXRiV: not found
/home/pschaefer/.ssh/id_rsa: 20: /home/pschaefer/.ssh/id_rsa: N9IN1Sxd6Dy7+qhz/qeE540uv2EezZZj1wFLoiF9fDcnHKD77t1ssRiU+jhNr5g1: not found
/home/pschaefer/.ssh/id_rsa: 21: /home/pschaefer/.ssh/id_rsa: 3XAIbr1dG3UHH5ppfEjNTTem6QbTbfZus1kPCrs+1jtCTieHlyo72KLVjV+crfC6: not found
/home/pschaefer/.ssh/id_rsa: 22: /home/pschaefer/.ssh/id_rsa: B9gAi6NSs4QdPxKpvXIFQTWcecYDQ9NeA/ovujgfK3/TBiro55+BmoHF0DIN7toU: not found
/home/pschaefer/.ssh/id_rsa: 23: /home/pschaefer/.ssh/id_rsa: tsSJIK5uiJQyxUjsVmDCufwhsKf/SJpfdo0FdO3Qp6FjhxwwqtjAzWHDLzxpgf5O: not found
/home/pschaefer/.ssh/id_rsa: 24: /home/pschaefer/.ssh/id_rsa: npn9WvqJjLMdaNVUev8J+mvwFHWfSmNHI9viVHUTkhFlUUIr5gCsnkCaSLWoyeAq: not found
/home/pschaefer/.ssh/id_rsa: 25: /home/pschaefer/.ssh/id_rsa: PFCCxJmhC2GJtmHyn5R0EkYglX0nZaFpuZdiHYs5kSLT5X5GhQ5YffKlf69xQrzf: not found
/home/pschaefer/.ssh/id_rsa: 26: /home/pschaefer/.ssh/id_rsa: 1FtfYTEgEdATOXfjZLoquyZ261Gr2GrcLbOutcq1XOGkbj2FCxkFO+23DSFYY/WY: not found
/home/pschaefer/.ssh/id_rsa: 27: /home/pschaefer/.ssh/id_rsa: YBG99aKCdW6LMHL0CzswhX9dbrcAMejp7upvRi7DP2WQGBOwzzwy3vVEt5jQaP7+: not found
/home/pschaefer/.ssh/id_rsa: 28: /home/pschaefer/.ssh/id_rsa: bfNYihY31pzbn9cFhTTaz2yrv8bLz6Q0LzhuhgyKN/1AnRE0GkF6NL0Z9fhO4eIj: not found
/home/pschaefer/.ssh/id_rsa: 29: /home/pschaefer/.ssh/id_rsa: n+7aOp6KR9txmEONOyUhpivud9XlC+00XU7YV9owS4/us3E08w+aG91WArC9I7jH: not found
/home/pschaefer/.ssh/id_rsa: 30: /home/pschaefer/.ssh/id_rsa: -----END: not found
root@167.99.176.218: Permission denied (publickey).
Failed to launch and connect to R worker on remote machine ‘167.99.176.218’ from local machine ‘TEMPLATE-trader’.
 * The error produced by socketConnection() was: ‘reached elapsed time limit’ (which suggests that the connection timeout of 120 seconds (argument 'connectTimeout') kicked in)
 * The localhost socket connection that failed to connect to the R worker used port 11963 using a communication timeout of 2592000 seconds and a connection timeout of 120 seconds.
 * Worker launch call: '/usr/bin/ssh' -R 11963:localhost:11963 -l root -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -i /home/pschaefer/.ssh/id_rsa 167.99.176.218 "'sudo' 'docker' 'run' '--net=host' 'rocker/tidyverse' 'Rscript' --default-packages=datasets,utils,grDevices,graphics,stats,methods -e \"install.packages('furrr')\" -e 'workRSOCK <- tryCatch(parallel:::.slaveRSOCK, error=function(e) parallel:::.workRSOCK); workRSOCK()' MASTER=localhost PORT=11963 OUT=/dev/null TIMEOUT=2592000 XDR=TRUE".
 * Troubleshooting suggestions:
   - Suggestion #1: Set 'outfile=NULL' to see output from worker.
   - Suggestion #2: Set 'rshlogfile=TRUE' to enable logging for ‘/usr/bin/ssh’.`

I suspect it has something to do with the ssh key, but I can't figure out what. I generated the key from within the droplet using `ssh-keygen`. I've tried adjusting the permissions using `sudo chmod 700 ~/.ssh/id_rsa` trying 600 and 700, but that didn't fix it. 

Any help would be greatly appreciated.
