### ISSUE TITLE
default password broken in docklet_rstudio

### ISSUE THREAD

**Issue by nielsaka** [sckott/analogsea#170]
Running the default example from the repository's README.md
```
docklet_create() %>%
  docklet_rstudio()
```
did not work out of the box. The browser opened but no connection was made. Apparently the containerized RStudio server rejects any passwords that are set to *rstudio*.

I found this out by loging into the droplet manually and starting the docker container, which gave
```
   ERROR: You must set a unique PASSWORD (not 'rstudio') first! e.g. run with:
docker run -e PASSWORD=<YOUR_PASS> -p 8787:8787 rocker/rstudio
```
Indeed, with a different password
```
docklet_create() %>%
  docklet_rstudio(password = "really_nice_r_package!")
```
it all works. I suggest modifying the default password [here](https://github.com/sckott/analogsea/blob/8f1f5698df5a58f42d3e22d6a03fc52082de595e/R/docklet.R#L203).

**Comment by sckott** [comment]
thanks @nielsaka for raising this issue. having a look at the PR
