### ISSUE TITLE
Problems spinning up a shiny app with docklet_shinyapp

### ISSUE THREAD

**Issue by studerus** [sckott/analogsea#179]
I tried to spin up a shiny app with docklet_shinyapp. It works fine using the example in the help file, but not with my own shiny app. It says "The application exited during initialization. "
I think the problem is that my shiny app uses R packages that are not installed on the shinyapp docklet. How can install additional packages? I tried the following, which did not work:
```
d %>% docklet_run("rocker/shiny", "Rscript -e 'install.packages(\"shinydashboard\")'")
```

Also, how can I get the error log to find out what error occurred in the shiny app?

**Comment by sckott** [comment]
session info please, as requested

**Comment by studerus** [comment]
I didn't provide the session info because the problem is not on the local machine, but here it is anyway:

```
R version 3.6.0 (2019-04-26)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=German_Switzerland.1252  LC_CTYPE=German_Switzerland.1252    LC_MONETARY=German_Switzerland.1252 LC_NUMERIC=C                       
[5] LC_TIME=German_Switzerland.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] analogsea_0.7.0

loaded via a namespace (and not attached):
[1] httr_1.4.0     compiler_3.6.0 magrittr_1.5   R6_2.4.0       tools_3.6.0    yaml_2.2.0     jsonlite_1.6
```

**Comment by sckott** [comment]
for seeing logs:

```r
# to get running containers
docklet_ps(d)
# get logs
droplet_ssh(d, "docker logs <container ID>")
```

**Comment by sckott** [comment]
for the dependencies:

```r
droplet_ssh(d, "docker exec <container ID> R -e 'install.packages(\"shinydashboard\")'")
```

make sure not to use `docker exec -ti` since it's not interactive

**Comment by studerus** [comment]
Thank you very much. It works. It would be great if you could add this to the documentation.
