### ISSUE TITLE
Droplet from local Dockerfile

### ISSUE THREAD

**Issue by athammad** [sckott/analogsea#194]
Hi,

first of all, thank you for this amazing package.

I was wandering if it would be possible to create a droplet based on a local `Dockerfile` (and all the folders and scripts in the local `Dockerfile` folder) rather than with an online image. 

Best wishes

**Comment by sckott** [comment]
thanks for using the pkg and for opening the issue @athammad 

there's nothing built in for that use case here, but you should be able to create a "docklet" (a droplet with docker installed) `docklet_create()`, then transfer your Dockerfile to the droplet, then do whatever docker commands.
