### ISSUE TITLE
Existing RStudio Images from the marketplace

### ISSUE THREAD

**Issue by pachamaltese** [sckott/analogsea#197]
Hi

Just to let you know that as an alternative to `docklet_create()`, I have this image with already configured full Tidyverse, RStudio Server and Shiny Server https://marketplace.digitalocean.com/apps/rstudio.

It can be created from the API with
```
curl -X POST -H 'Content-Type: application/json' \
     -H 'Authorization: Bearer '$TOKEN'' -d \
    '{"name":"choose_a_name","region":"sfo2","size":"s-2vcpu-4gb","image":"simplystatistics-rstudio-18-04"}' \
    "https://api.digitalocean.com/v2/droplets"
```

I have more images (https://marketplace.digitalocean.com/apps/rstudio-pkgdev and https://marketplace.digitalocean.com/apps/rstudio-h2o) that I created during Dr. Le Dell and Dr. Wickham for the last Latin R in Chile.

**Comment by sckott** [comment]
thanks @pachamaltese 

looks like it can be used like:

```r
docklet_create(image = "simplystatistics-rstudio-18-04")
```

maybe you meant to say, instead of the function `docklet_rstudio`?

**Comment by pachamaltese** [comment]
> thanks @pachamaltese
> 
> looks like it can be used like:
> 
> ```r
> docklet_create(image = "simplystatistics-rstudio-18-04")
> ```
> 
> maybe you meant to say, instead of the function `docklet_rstudio`?

yes, that's an inside-R option
thanks a lot for expressing my idea in shorter terms :)
