### ISSUE TITLE
Any thoughts on CRAN update?

### ISSUE THREAD

**Issue by muschellij2** [sckott/analogsea#201]
Will close after a week if no response.   Just wondering if there is a timeline for submit to CRAN - didn't see a timeline.  Not trying to pressure, just want to get some timelines down for `plumberDeploy` package: https://github.com/meztez/plumberDeploy, which now relies on some of the new functions of analogsea using the `...` pass throughs from #199.  We still need to coordinate with plumber maintainers to ensure no break when new submission, but I think analogsea cran update may need to come first.

**Comment by sckott** [comment]
i'll try for today

**Comment by sckott** [comment]
submitting now

**Comment by sckott** [comment]
accepted
