### ISSUE TITLE
Figure out how to use ssh shipped with Rstudio

### ISSUE THREAD

**Issue by hadley** [sckott/analogsea#81]
For windows - found in `RStudio\bin\msys_ssh`

**Comment by sckott** [comment]
Do you think it's best to use RStudio `ssh`/`scp` when on linux and mac too? Or just windows?

**Comment by MarkEdmondson1234** [comment]
Hi @sckott have you tried this out?  I've used your ssh/scp code at googleComputeEngineR, and getting people having issues on Windows trying to connect.  Using a version shipped with RStudio sounds cool.

**Comment by sckott** [comment]
i haven't tried yet - will try to get to soon and get back to you

**Comment by MarkEdmondson1234** [comment]
@sckott a little development, it looks as if the RStudio SSH client has a hardcoded place to put SSH keys, so potentially you could use those to authenticate.  I'm in the same position as you in having trouble getting a Windows machine to fully test it https://github.com/cloudyr/googleComputeEngineR/issues/32#issuecomment-277599012

**Comment by sckott** [comment]
thx, will have a look soon
